SRC += features/custom_shift_keys.c

REPEAT_KEY_ENABLE = yes
LAYER_LOCK_ENABLE = yes

CONSOLE_ENABLE = yes
DEBUG_TOGGLE=yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
