SRC += features/custom_shift_keys.c

KEY_OVERRIDE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
KEYCODE_STRING_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
